# order_service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: athishulleri/order-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_DB
          value: order_db
        - name: POSTGRES_USER
          value: order_db_user
        - name: POSTGRES_PASSWORD
          value: order_db_password
