# # user_service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-backend
        image: athishulleri/users-user-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "user_service.settings"
        - name: DATABASE_ENGINE
          value: "django.db.backends.postgresql"
        - name: DATABASE_NAME
          value: "user_service"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: DATABASE_HOST
          value: "postgres_user"
        - name: DATABASE_PORT
          value: "5432"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: user-service
#   template:
#     metadata:
#       labels:
#         app: user-service
#     spec:
#       containers:
#       - name: user-service
#         image: athishulleri/user-user-service:latest
#         ports:
#         - containerPort: 8000
#         env:
#         - name: POSTGRES_DB
#           value: user_db
#         - name: POSTGRES_USER
#           value: user_db_user
#         - name: POSTGRES_PASSWORD
#           value: user_db_password
