apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer




# # service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: miniproject-backend-service
# spec:
#   selector:
#     app: miniproject-backend
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: django-service
# spec:
#   selector:
#     app: django-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#   type: LoadBalancer
