apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-sevice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice-backend
        image: athishulleri/userrservice-email:latest  # Replace with your Docker image name
        ports:
        - containerPort: 8001
        
